version: '3.9'
services:
  db:
    image: postgres
    container_name: edu-app-db
    env_file:
      - .env
    restart: on-failure
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  s3:
    image: minio/minio
    container_name: edu-minio
    volumes:
      - ./storage/minio:/data
    env_file:
      - .env
    ports:
      - "9000:9000"
      - "9001:9001"
    command: server /data --console-address :9001
    restart: on-failure

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: edu-app
    env_file:
      - .env
    ports:
      - "8080:8080"
    depends_on:
      - db
      - s3
    restart: on-failure
