spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/education-app-db
    username: postgres
    password: 1234

  jpa:
    show-sql: true

s3:
  secret-key: kueDXThyvYzPNt8t5HTJPUYuV2T8ebWvGpKAzfhQ
  access-key: xqg2VlFtvGu4bnelcsS0
  bucket-name: edu-app
  endpoint: http://localhost:9000