server:
  port: 8080
spring:
  application:
    name: edu
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_URL}/${DB_TABLE_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
  liquibase:
    change-log: liquibase/changelog.yml
    driver-class-name: org.postgresql.Driver
s3:
  secret-key: ${S3_SECRET_KEY}
  access-key: ${S3_SECRET_KEY}
  bucket-name: ${S3_BUCKET_NAME}
