spring:
  application:
    name: edu
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/semester
    username: postgres
    password: 1234

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false